feat: реализовать сервисы - пользователям возможность добавлять в дру…
KirillBabichenko/java-filmorate pull request #4
Opened 2023-01-05 21:17 UTC by KirillBabichenko

…зья и ставить лайки фильмам

2023-01-06 16:47 UTC, AnastasiyaFomkina requested changes

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
Лучше тоже переименовать в `exception`

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Так как мы используем `lombok` лучше будет инжектить поля с помощью аннотации [@RequiredArgsConstructor](https://www.baeldung.com/spring-injection-lombok#constructor-injection-with-lombok:~:text=Constructor%20Injection%20With%20Lombok). Она поможет избавиться от однотипных конструкторов и немного сократить код

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        checkForPositivity(id);
Лучше заменить проверку на `@PositiveOrZero` у параметра, так валидация полей будет происходить автоматически. Важно добавить аннотацию `@Validated` над контроллером, чтобы проверки работали корректно
<img width="329" alt="Снимок экрана 2023-01-06 в 19 28 43" src="https://user-images.githubusercontent.com/43168217/211054877-68577621-89ca-4a5f-8a21-41696cd42d92.png">

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkForPositivity(Long id) {
Если решишь не использовать автоматическую валидацию, лучше перенести проверки в слой сервиса, так как сервисный слой отвечает за бизнес-логику программы и правильнее делать все проверки в нем

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController {
Тут лучше поправить все тоже самое, что и в контроллере фильмов

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public ErrorResponse(String error, String description) {
Лучше заменить весь бойлерплейт на аннотации lombok: `@Getter`, `@AllArgsConstructor`
Вот [здесь](https://habr.com/ru/company/piter/blog/676394/) отличное руководство по lombok с примерами и тем, как аннотации работают под капотом

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +import lombok.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (!(inMemoryUserStorage.getUsers().get(id).getFriends().contains(idFriend))) {
Лишние скобочки
```suggestion
        if (!inMemoryUserStorage.getUsers().get(id).getFriends().contains(idFriend)) {
```

2023-01-06 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        System.out.println(idUser);
Лучше использовать логирование, вывод в консоль менее удобен и нельзя автоматизировать его сохранение

2023-01-07 01:58 UTC, KirillBabichenko commented on src/main/java/ru/yandex/practicum/filmorate/model/ErrorResponse.java
> +    public ErrorResponse(String error, String description) {
Спасибо! Отличная статья!

2023-01-07 01:59 UTC, KirillBabichenko commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +import lombok.*;
Спасибо!

2023-01-07 02:11 UTC, KirillBabichenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkForPositivity(Long id) {
Решил оставить свою валидацию перенеся метод в сервисный слой. Не понимаю и не нашел, как можно изменить код ответа при автоматической проверке @PositiveOrZero. В одном из тестов Postman при отрицательном значении параметра ожидается ответ 404, а выбрасывается 500.

2023-01-08 09:45 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void checkForPositivity(Long id) {
Да, там надо перенастраивать коды ошибок в настройках проекта, пока действительно лучше оставить твой вариант

2023-01-08 09:46 UTC, AnastasiyaFomkina approved these changes

2023-01-08 16:59 UTC, merged