feat: Добавить возможность работать с базой данных.
KirillBabichenko/java-filmorate pull request #7
Opened 2023-02-06 00:43 UTC by KirillBabichenko

2023-02-06 21:00 UTC, AnastasiyaFomkina requested changes

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
Пока нам данная зависимость не нужна - лучше удалить

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    final private DbFilmService dbFilmService;
Нужно обозначать переменную интерфейсом: `FilmStorage`

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    final private DbUserService dbUserService;
Лучше обозначать интерфейс, а не конкретную реализацию

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Так как логирование не используется в данном классе, лучше его удалить

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Setter
`@Getter` и `@Setter` тоже лишние, так как нигде нам не понадобятся

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Setter
Посмотри, пожалуйста, есть ли лишние аннотации в других классах и удали ненужные

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      @PostMapping("/films")
Можно вынести повторяющийся путь `"/films"` в аннотацию [@RequestMapping](https://www.baeldung.com/spring-requestmapping), так можно будет избавиться от дублирований. Добавь, пожалуйста, во всех других контроллерах

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +        throw new DatabaseException("При записи фильма в базу данных произошла ошибка");
У `Optional` есть множество методов, которые упрощают работу с оберткой, например `.orElseThrow()` достает значение из `optional`, если оно существует, а если `optional` пуст - выбрасывает исключение.
Вот подробная [статья](https://habr.com/ru/post/346782/) про `Optional`.
Предлагаю попробовать переписать с помощью уже готовых методов

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +    private final DaoFilmService daoFilmService;
Лучше переименовать все классы, которые занимаются обработкой логики базы данных просто в `FilmDao` или `...Repository`, так будет выглядеть логичнее, потому что `Service` обычно отвечают за бизнес-логику программы

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
>  public interface FilmStorage {
Данный интерфейс должен реализовывать новый класс, который занимается хранением данных, а не класс-сервис. Нужно также поправить для `UserStorage`

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/validation/PositivityChecker.java
> +public class PositivityChecker {
👍

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        if (inMemoryUserStorage.getUsers().get(idFriend).getUnverifiedFriends().contains(id)) {
Можно добавить старым классам описание, что взамен используется реализация с хранением данных в базе-данных. Это можно сделать с помощью комментариев или [java doc](https://java-online.ru/java-javadoc.xhtml)

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DaoFilmService.java
> +public class DaoFilmService implements DaoFilm {
Нужно переименовать название классов, которые занимаются хранением данных в бд. Классы для фильмов и пользователей, должны реализовывать старые интерфейсы

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DaoMpaService.java
> +        log.info("Мы в дао - креате мпа");
Похоже, что данный лог был добавлен для отладки :)

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/dao/DaoUserService.java
> +        String sql = "SELECT * FROM Users WHERE id_user IN (SELECT id_friends FROM " +
Нужно избавиться от множественной вложености запросов. Можно обратиться к наставнику за помощью в решении данной проблемы

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
>  public class FilmControllerTest {
Тесты с валидацией удалять ненужно. Лучше доработать с учетом новой реализации. 
Можно посмотреть в сторону [@SpringBootTest](https://www.baeldung.com/spring-boot-testing)

2023-02-06 21:00 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
>  public class UserControllerTest {
Лучше не удалять тест, а поправить его под новую реализацию

2023-02-06 22:26 UTC, KirillBabichenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    final private DbFilmService dbFilmService;
Я запутался в логике, особенно из-за комментария ниже, что интерфейс FilmStorage должен реализовывать новый класс который работает с БД - DaoFilmService.  Если я правильно понимаю, то нужно переписать текущий DaoFilmService имплементировать его от FilmStorage? И написать новый интерфейс FilmService который будет реализовывать текущий DbFilmService и уже в контроллере обозначить переменную FilmService?

2023-02-06 22:45 UTC, KirillBabichenko commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +    private final DaoFilmService daoFilmService;
Этот класс как мне кажется и является сервисом, который работает с логикой программы. Может быть с его названием тут все же правильно? только имплементация некорректная? Возможно имеется ввиду, что нужно переименовать классы в пакете dao - DaoFilmService и остальные, которые я некорректно назвал сервисами?

2023-02-07 00:48 UTC, KirillBabichenko commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +        throw new DatabaseException("При записи фильма в базу данных произошла ошибка");
Спасибо, отличная статья! Как раз хотел подтянуть знания по Optional. А есть возможность посоветовать еще такие же качественные по стримам и лямбдам?

2023-02-08 10:41 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    final private DbFilmService dbFilmService;
Вот схематичное представление взаимодействия между слоями программы:
<img width="631" alt="Снимок экрана 2023-02-08 в 13 28 17" src="https://user-images.githubusercontent.com/43168217/217506078-94d01501-2cf5-4d44-9fc3-be2129f2be32.png">

Получается, в прошлых спринтах мы хранили все данные в памяти, а сейчас мы написали новую реализацию хранения данных - в базе данных. То есть интерфейс взаимодействия с записью данных должен был остаться старым, а на его основе должна быть создана новая реализация `dao` или `repository` или `dbstorage`, как предлагается ее назвать в тз:
<img width="747" alt="Снимок экрана 2023-02-08 в 13 31 59" src="https://user-images.githubusercontent.com/43168217/217506819-eea15bfa-4fa1-4464-9639-81e8fc481d2f.png">

Также можно добавить интерфейс между прослойкой контроллера и сервиса, но это необязательно, так как других вариантов реализации сервиса мы не планируем создавать

2023-02-08 10:51 UTC, AnastasiyaFomkina requested changes
Подробно прописала схему взаимодействия всех слоев программы в вопросе выше. Предлагаю поправить взаимодействие по схемам, которые приложила. Так же оставила небольшой комментарий про инжект полей, поправь, пожалуйста

2023-02-08 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +    private final DaoLikeRepository daoLikeRepository;
Если класс реализует какой-либо интерфейс, то при инициализации данного класса в другом, нужно обозначать интерфейс, который он наследует:
```suggestion
    private final DaoLike daoLikeRepository;
```
А спринг уже автоматически выберет и подставит нужную нам реализацию. Таким образом, мы не сломаем программу, если одну из реализаций нужно будет удалить или дополнить

2023-02-08 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/DbFilmService.java
> +    private final DaoLikeRepository daoLikeRepository;
Поправь, пожалуйста, по всему проекту

2023-02-08 10:51 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    final private DbFilmService dbFilmService;
Для новых классов схема взаимодействия будет чуть проще, так как для них не было реализовано хранение данных в памяти:
<img width="297" alt="Снимок экрана 2023-02-08 в 13 47 46" src="https://user-images.githubusercontent.com/43168217/217508773-6a827a2f-dd0a-4f59-a8a4-240fa5b5871c.png">
Опять же прослойка с интерфейсом для сервиса - опциональна, так как других реализаций сервиса не планируется

2023-02-09 08:20 UTC, AnastasiyaFomkina approved these changes

2023-02-09 10:36 UTC, merged